### PR TITLE
[7.67.x] [RHDM-1994] Performance degradation when increasing concurrency of rule execution in multi threads

### PR DESCRIPTION
**Pull request by tkobayas**
**Ports** 

This is a backport PR of DROOLS-7521 + additional fix for 7.67.x

**JIRA**: 
https://issues.redhat.com/browse/RHDM-1994

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

 - for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
@lucamolteni @mariofusco Please review, if CIs are okay.

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
@mariofusco This PR has 2 commits. Please don't squash on merge. Thanks!

**Comment by tkobayas** [comment]
CDB: Not related to this PR
```
[2023-10-30T08:57:21.082Z] WARN: Failed to define class org.jboss.as.domain.http.server.ConsoleAvailabilityService$LogAdminConsole in Module "org.jboss.as.domain-http-interface" version 15.0.0.Final from local module loader @fba98ec (finder: local module finder @638e65b8 (roots: /home/jenkins/workspace/KIE/7.67.x/compile/drools-7.67.x.compile/bc/kiegroup_kie-wb-distributions/business-central-parent/business-monitoring-webapp/target/bootable-jar-build-artifacts/wildfly/modules,/home/jenkins/workspace/KIE/7.67.x/compile/drools-7.67.x.compile/bc/kiegroup_kie-wb-distributions/business-central-parent/business-monitoring-webapp/target/bootable-jar-build-artifacts/wildfly/modules/system/layers/base))
[2023-10-30T08:57:21.082Z] org.jboss.modules.ModuleLoadError: org.wildfly.security.elytron-web.undertow-server
```

PR: Not likely related to this PR
```
[2023-10-30T08:40:18.111Z] [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default) on project drools-retediagram: Could not find a default branch for project with key 'org.drools:drools'. Make sure project exists. -> [Help 1]
```

FDB : Not related to this PR
```
[2023-10-30T10:33:04.206Z] [ERROR] Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 20.752 s <<< FAILURE! - in org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest
[2023-10-30T10:33:04.206Z] [ERROR] testCreateContainerNonExistingGAV2[JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:45511/kie-server-services/services/rest/server'}](org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest)  Time elapsed: 10.277 s  <<< ERROR!
[2023-10-30T10:33:04.206Z] java.lang.RuntimeException: Unexpected exception creating container: no-gav2-container with release-id foo:bar:0.0.0
[2023-10-30T10:33:04.206Z]      at org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerNonExistingGAV2(RestMalformedRequestIntegrationTest.java:46)
[2023-10-30T10:33:04.206Z] Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: java.net.SocketTimeoutException: Read timed out
[2023-10-30T10:33:04.206Z]      at org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerNonExistingGAV2(RestMalformedRequestIntegrationTest.java:41)
[2023-10-30T10:33:04.206Z] Caused by: java.net.SocketTimeoutException: Read timed out
[2023-10-30T10:33:04.206Z]      at org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerNonExistingGAV2(RestMalformedRequestIntegrationTest.java:41)
[2023-10-30T10:33:04.206Z]
[2023-10-30T10:33:04.206Z] [ERROR] testCreateContainerNonExistingGAV2[JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:45511/kie-server-services/services/rest/server'}](org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest)  Time elapsed: 10.123 s  <<< ERROR!
[2023-10-30T10:33:04.206Z] java.lang.RuntimeException: Unexpected exception creating container: no-gav2-container with release-id foo:bar:0.0.0
[2023-10-30T10:33:04.206Z]      at org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerNonExistingGAV2(RestMalformedRequestIntegrationTest.java:46)
[2023-10-30T10:33:04.206Z] Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: java.net.SocketTimeoutException: Read timed out
[2023-10-30T10:33:04.206Z]      at org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerNonExistingGAV2(RestMalformedRequestIntegrationTest.java:41)
[2023-10-30T10:33:04.206Z] Caused by: java.net.SocketTimeoutException: Read timed out
[2023-10-30T10:33:04.206Z]      at org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerNonExistingGAV2(RestMalformedRequestIntegrationTest.java:41)

...


[2023-10-30T14:25:16.574Z] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 34.103 s <<< FAILURE! - in org.kie.bc.DeploymentIT
[2023-10-30T14:25:16.574Z] [ERROR] org.kie.bc.DeploymentIT  Time elapsed: 34.096 s  <<< ERROR!
[2023-10-30T14:25:16.574Z] org.jboss.arquillian.container.spi.client.container.DeploymentException:
[2023-10-30T14:25:16.574Z] Cannot deploy business-monitoring-webapp.war: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"business-monitoring-webapp.war\".WeldStartService" => "Failed to start service
[2023-10-30T14:25:16.574Z]     Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-000049: Unable to invoke public void org.guvnor.structure.backend.repositories.LoadReposOnAppInit.execute() on org.guvnor.structure.backend.repositories.LoadReposOnAppInit@1897e50c
[2023-10-30T14:25:16.574Z]     Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void org.guvnor.structure.backend.repositories.LoadReposOnAppInit.execute() on org.guvnor.structure.backend.repositories.LoadReposOnAppInit@1897e50c
[2023-10-30T14:25:16.574Z]     Caused by: java.lang.reflect.InvocationTargetException
[2023-10-30T14:25:16.574Z]     Caused by: org.uberfire.java.nio.file.FileSystemNotFoundException: No filesystem for uri (default://system/system) found."}}}}

...

[2023-10-30T14:54:37.782Z] [ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 150.951 s <<< FAILURE! - in org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest
[2023-10-30T14:54:37.782Z] [ERROR] importAndBuildProjectFromStockRepository(org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest)  Time elapsed: 37.435 s  <<< ERROR!
[2023-10-30T14:54:37.782Z] org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.id: add-project-dropdown (tried for 15 second(s) with 500 milliseconds interval)
[2023-10-30T14:54:37.782Z]      at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.lambda$importAndBuildProjectFromStockRepository$0(ProjectLibraryIntegrationTest.java:51)
[2023-10-30T14:54:37.782Z]      at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importBuildDeployAndCheckArtifact(ProjectLibraryIntegrationTest.java:68)
[2023-10-30T14:54:37.782Z]      at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository(ProjectLibraryIntegrationTest.java:49)
[2023-10-30T14:54:37.782Z] Caused by: org.openqa.selenium.NoSuchElementException:
[2023-10-30T14:54:37.782Z] Cannot locate an element using By.id: add-project-dropdown
[2023-10-30T14:54:37.782Z] For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
[2023-10-30T14:54:37.782Z] Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
[2023-10-30T14:54:37.782Z] System info: host: 'eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.99.1.el7.x86_64', java.version: '11.0.15'
[2023-10-30T14:54:37.782Z] Driver info: driver.version: unknown
[2023-10-30T14:54:37.782Z]      at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.lambda$importAndBuildProjectFromStockRepository$0(ProjectLibraryIntegrationTest.java:51)
[2023-10-30T14:54:37.782Z]      at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importBuildDeployAndCheckArtifact(ProjectLibraryIntegrationTest.java:68)
[2023-10-30T14:54:37.782Z]      at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository(ProjectLibraryIntegrationTest.java:49)
```

**Review by mariofusco — APPROVED** [review]

**Review by lucamolteni — APPROVED** [review]

**Pull request merged**
